import { Developer } from "@/components/dashboard/table/columns";
import { IDeveloper } from "@/types";

export const developersData: IDeveloper[] = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    avatarUrl: "https://i.pravatar.cc/150?img=1",
    role: "Frontend Developer",
    currentProjectId: null,
    projectsCount: 0,
    githubUrl: "https://github.com/alicejohnson",
    techStack: ["React", "TypeScript", "Tailwind CSS"],
  },
  {
    id: "2",
    name: "Bob Smith",
    email: "bob.smith@example.com",
    avatarUrl: "https://i.pravatar.cc/150?img=2",
    role: "Backend Developer",
    currentProjectId: "1",
    projectsCount: 1,
    githubUrl: "https://github.com/bsmith",
    techStack: ["Node.js", "Express", "PostgreSQL"],
  },
  {
    id: "3",
    name: "Clara Lee",
    email: "clara.lee@example.com",
    avatarUrl: "https://i.pravatar.cc/150?img=3",
    role: "Fullstack Developer",
    currentProjectId: "1",
    projectsCount: 2,
    githubUrl: "https://github.com/claralee",
    techStack: ["React", "Node.js", "MongoDB"],
  },
  {
    id: "4",
    name: "David Brown",
    email: "david.brown@example.com",
    avatarUrl: "https://i.pravatar.cc/150?img=4",
    role: "DevOps Engineer",
    currentProjectId: "2",
    projectsCount: 3,
    githubUrl: "https://github.com/dbrown",
    techStack: ["Docker", "Kubernetes", "AWS"],
  },
  {
    id: "5",
    name: "Evelyn White",
    email: "evelyn.white@example.com",
    avatarUrl: "https://i.pravatar.cc/150?img=5",
    role: "Mobile Developer",
    currentProjectId: null,
    projectsCount: 4,
    githubUrl: "https://github.com/evelynwhite",
    techStack: ["React Native", "Flutter", "Firebase"],
  },
];

export const mockDevelopers: Developer[] = [
  {
    id: "dev1",
    name: "Alice Santos",
    activeProjectsCount: 3,
    status: "approved",
    level: "senior",
  },
  {
    id: "dev2",
    name: "Carlos Pereira",
    activeProjectsCount: 0,
    status: "pending",
    level: "junior",
  },
  {
    id: "dev3",
    name: "Beatriz Costa",
    activeProjectsCount: 5,
    status: "approved",
    level: "mid_level",
  },
  {
    id: "dev4",
    name: "Diego Almeida",
    activeProjectsCount: 0,
    status: "rejected",
    level: "senior",
  },
  {
    id: "dev5",
    name: "Fernanda Oliveira",
    activeProjectsCount: 0,
    status: "pending",
    level: "mid_level",
  },
  {
    id: "dev6",
    name: "Gabriel Souza",
    activeProjectsCount: 4,
    status: "approved",
    level: "junior",
  },
  {
    id: "dev7",
    name: "Helena Martins",
    activeProjectsCount: 6,
    status: "approved",
    level: "senior",
  },
  {
    id: "dev8",
    name: "Igor Ribeiro",
    activeProjectsCount: 0,
    status: "rejected",
    level: "mid_level",
  },
  {
    id: "dev9",
    name: "Juliana Mendes",
    activeProjectsCount: 0,
    status: "pending",
    level: "junior",
  },
  {
    id: "dev10",
    name: "Lucas Ferreira",
    activeProjectsCount: 5,
    status: "approved",
    level: "senior",
  },
];
