import { IDeveloper } from "@/types";

export const developersData: IDeveloper[] = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    avatarUrl: "https://i.pravatar.cc/150?img=1",
    role: "Frontend Developer",
    currentProjectId: null,
    projectsCount: 0,
    githubUrl: "https://github.com/alicejohnson",
    techStack: ["React", "TypeScript", "Tailwind CSS"],
  },
  {
    id: "2",
    name: "Bob Smith",
    email: "bob.smith@example.com",
    avatarUrl: "https://i.pravatar.cc/150?img=2",
    role: "Backend Developer",
    currentProjectId: "1",
    projectsCount: 1,
    githubUrl: "https://github.com/bsmith",
    techStack: ["Node.js", "Express", "PostgreSQL"],
  },
  {
    id: "3",
    name: "Clara Lee",
    email: "clara.lee@example.com",
    avatarUrl: "https://i.pravatar.cc/150?img=3",
    role: "Fullstack Developer",
    currentProjectId: "1",
    projectsCount: 2,
    githubUrl: "https://github.com/claralee",
    techStack: ["React", "Node.js", "MongoDB"],
  },
  {
    id: "4",
    name: "David Brown",
    email: "david.brown@example.com",
    avatarUrl: "https://i.pravatar.cc/150?img=4",
    role: "DevOps Engineer",
    currentProjectId: "2",
    projectsCount: 3,
    githubUrl: "https://github.com/dbrown",
    techStack: ["Docker", "Kubernetes", "AWS"],
  },
  {
    id: "5",
    name: "Evelyn White",
    email: "evelyn.white@example.com",
    avatarUrl: "https://i.pravatar.cc/150?img=5",
    role: "Mobile Developer",
    currentProjectId: null,
    projectsCount: 4,
    githubUrl: "https://github.com/evelynwhite",
    techStack: ["React Native", "Flutter", "Firebase"],
  },
];
