import { Tag } from "@/types";

export const technologySlugs = [
  "typescript",
  "javascript",
  "dart",
  "java",
  "react",
  "flutter",
  "android",
  "html5",
  "css3",
  "nodedotjs",
  "express",
  "nextdotjs",
  "prisma",
  "amazonaws",
  "postgresql",
  "firebase",
  "nginx",
  "vercel",
  "testinglibrary",
  "jest",
  "cypress",
  "docker",
  "git",
  "jira",
  "github",
  "gitlab",
  "visualstudiocode",
  "androidstudio",
  "sonarqube",
  "figma",
  "springboot",
];

export const technologyTags: Tag[] = [
  // Frontend
  { id: "react", label: "React" },
  { id: "angular", label: "Angular" },
  { id: "vue", label: "Vue.js" },
  { id: "svelte", label: "Svelte" },
  { id: "solid", label: "Solid.js" },
  { id: "next", label: "Next.js" },
  { id: "nuxt", label: "Nuxt.js" },
  { id: "gatsby", label: "Gatsby" },
  { id: "remix", label: "Remix" },
  { id: "astro", label: "Astro" },
  { id: "html", label: "HTML5" },
  { id: "css", label: "CSS3" },
  { id: "sass", label: "Sass" },
  { id: "tailwind", label: "Tailwind CSS" },
  { id: "bootstrap", label: "Bootstrap" },
  { id: "materialui", label: "Material UI" },
  { id: "chakra", label: "Chakra UI" },
  { id: "storybook", label: "Storybook" },
  { id: "jest", label: "Jest" },
  { id: "testing-library", label: "Testing Library" },
  { id: "cypress", label: "Cypress" },
  { id: "playwright", label: "Playwright" },

  // Backend
  { id: "node", label: "Node.js" },
  { id: "express", label: "Express" },
  { id: "nestjs", label: "NestJS" },
  { id: "fastify", label: "Fastify" },
  { id: "spring", label: "Spring Boot" },
  { id: "django", label: "Django" },
  { id: "flask", label: "Flask" },
  { id: "laravel", label: "Laravel" },
  { id: "rails", label: "Ruby on Rails" },
  { id: "aspnet", label: "ASP.NET" },
  { id: "graphql", label: "GraphQL" },
  { id: "rest", label: "REST API" },
  { id: "grpc", label: "gRPC" },
  { id: "tRPC", label: "tRPC" },
  { id: "socketio", label: "Socket.IO" },

  // Languages
  { id: "typescript", label: "TypeScript" },
  { id: "javascript", label: "JavaScript" },
  { id: "python", label: "Python" },
  { id: "java", label: "Java" },
  { id: "kotlin", label: "Kotlin" },
  { id: "swift", label: "Swift" },
  { id: "csharp", label: "C#" },
  { id: "fsharp", label: "F#" },
  { id: "php", label: "PHP" },
  { id: "ruby", label: "Ruby" },
  { id: "go", label: "Go" },
  { id: "rust", label: "Rust" },
  { id: "elixir", label: "Elixir" },
  { id: "scala", label: "Scala" },
  { id: "clojure", label: "Clojure" },
  { id: "dart", label: "Dart" },

  // Mobile
  { id: "reactnative", label: "React Native" },
  { id: "flutter", label: "Flutter" },
  { id: "ionic", label: "Ionic" },
  { id: "android", label: "Android" },
  { id: "ios", label: "iOS" },
  { id: "swiftui", label: "SwiftUI" },
  { id: "jetpackcompose", label: "Jetpack Compose" },

  // Cloud & DevOps
  { id: "aws", label: "AWS" },
  { id: "azure", label: "Azure" },
  { id: "gcp", label: "Google Cloud" },
  { id: "digitalocean", label: "DigitalOcean" },
  { id: "vercel", label: "Vercel" },
  { id: "netlify", label: "Netlify" },
  { id: "heroku", label: "Heroku" },
  { id: "docker", label: "Docker" },
  { id: "kubernetes", label: "Kubernetes" },
  { id: "terraform", label: "Terraform" },
  { id: "ansible", label: "Ansible" },
  { id: "jenkins", label: "Jenkins" },
  { id: "github-actions", label: "GitHub Actions" },
  { id: "gitlab-ci", label: "GitLab CI" },
  { id: "argo", label: "Argo CD" },

  // Databases
  { id: "mongodb", label: "MongoDB" },
  { id: "postgresql", label: "PostgreSQL" },
  { id: "mysql", label: "MySQL" },
  { id: "sqlserver", label: "SQL Server" },
  { id: "oracle", label: "Oracle" },
  { id: "sqlite", label: "SQLite" },
  { id: "redis", label: "Redis" },
  { id: "elasticsearch", label: "Elasticsearch" },
  { id: "firebase", label: "Firebase" },
  { id: "supabase", label: "Supabase" },
  { id: "prisma", label: "Prisma" },
  { id: "typeorm", label: "TypeORM" },
  { id: "dynamodb", label: "DynamoDB" },
  { id: "cassandra", label: "Cassandra" },
  { id: "neo4j", label: "Neo4j" },

  // Tools & Platforms
  { id: "git", label: "Git" },
  { id: "github", label: "GitHub" },
  { id: "gitlab", label: "GitLab" },
  { id: "bitbucket", label: "Bitbucket" },
  { id: "jira", label: "Jira" },
  { id: "trello", label: "Trello" },
  { id: "figma", label: "Figma" },
  { id: "sketch", label: "Sketch" },
  { id: "xd", label: "Adobe XD" },
  { id: "vscode", label: "VS Code" },
  { id: "intellij", label: "IntelliJ IDEA" },
  { id: "webstorm", label: "WebStorm" },
  { id: "vim", label: "Vim" },
  { id: "emacs", label: "Emacs" },
  { id: "postman", label: "Postman" },
  { id: "insomnia", label: "Insomnia" },
  { id: "swagger", label: "Swagger" },
  { id: "sentry", label: "Sentry" },
  { id: "datadog", label: "Datadog" },
  { id: "newrelic", label: "New Relic" },

  // Emerging Technologies
  { id: "ai", label: "AI/ML" },
  { id: "tensorflow", label: "TensorFlow" },
  { id: "pytorch", label: "PyTorch" },
  { id: "blockchain", label: "Blockchain" },
  { id: "web3", label: "Web3" },
  { id: "solidity", label: "Solidity" },
  { id: "wasm", label: "WebAssembly" },
  { id: "deno", label: "Deno" },
  { id: "bun", label: "Bun" },
  { id: "electron", label: "Electron" },
  { id: "tauri", label: "Tauri" },
  { id: "threejs", label: "Three.js" },
  { id: "webgl", label: "WebGL" },
  { id: "pwa", label: "PWA" },
  { id: "serverless", label: "Serverless" },
  { id: "microservices", label: "Microservices" },
  { id: "edge", label: "Edge Computing" },
];
