export const demoPlans = [
    {
      name: "BÁSICO",
      price: "50",
      yearlyPrice: "40",
      period: "por mês",
      features: [
        "Até 3 projetos",
        "Análises básicas",
        "Tempo de resposta do suporte em até 48 horas",
        "Acesso limitado ao acompanhamento",
        "Suporte dos desenvolvedores",
      ],
      description: "Perfeito para indivíduos e pequenos projetos",
      isPopular: false,
    },
    {
      name: "PROFISSIONAL",
      price: "99",
      yearlyPrice: "79",
      period: "por mês",
      features: [
        "Projetos ilimitados",
        "Análises avançadas",
        "Tempo de resposta do suporte em até 24 horas",
        "Acesso completo ao acompanhamento",
        "Suporte prioritário",
        "Colaboração com equipe",
        "Integrações personalizadas",
      ],
      description: "Ideal para equipes em crescimento e negócios",
      isPopular: true,
    },
    {
      name: "EMPRESARIAL",
      price: "299",
      yearlyPrice: "239",
      period: "por mês",
      features: [
        "Tudo no plano Profissional",
        "Soluções personalizadas",
        "Gerente de conta dedicado",
        "Tempo de resposta do suporte em até 1 hora",
        "Autenticação SSO",
        "Segurança avançada",
        "Contratos personalizados",
        "Acordo de Nível de Serviço (SLA)",
      ],
      description: "Para grandes organizações com necessidades específicas",
      isPopular: false,
    },
  ];